### ISSUE TITLE
Running sudo inside program does nothing if you start with sudo

### ISSUE THREAD

**Issue by dko1905** [HUSKI3/Spark#5]
The `--no-sudo` argument and the usage of sudo in the program has no function if the package manager is run with sudo.
Since child processes inherit the privileges of the parent process, there is no reason to use sudo in the `os.system()` calls.
Here is an example of this:
![sudo-not-required](https://user-images.githubusercontent.com/44919636/123103915-bf6f5880-d436-11eb-9499-06ac9b7d5d2a.png)

**Comment by HUSKI3** [comment]
Sudo is required for elevated permissions to move files globally for system installs. It's not used right now due to us rewriting the package behavior. If you use the older releases of Spark on systems with no users, "--no-sudo" is a required parameter.

**Comment by HUSKI3** [comment]
But yes you are right, we will remove the sudo references once we've finished other functionality
